### ISSUE TITLE
[1.3.0][Distribution][BUG] Job Scheduler failed the 1.3.0 build due to failed to apply plugin class 'org.opensearch.gradle.info.GlobalBuildInfoPlugin'.

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/job-scheduler#135]
```
2022-03-08 16:42:15 INFO     Building job-scheduler
2022-03-08 16:42:15 INFO     Executing "git init" in /tmp/tmp8d7oail8/job-scheduler
2022-03-08 16:42:15 INFO     Executing "git remote add origin https://github.com/opensearch-project/job-scheduler.git" in /tmp/tmp8d7oail8/job-scheduler
2022-03-08 16:42:15 INFO     Executing "git fetch --depth 1 origin main" in /tmp/tmp8d7oail8/job-scheduler
2022-03-08 16:42:15 INFO     Executing "git checkout FETCH_HEAD" in /tmp/tmp8d7oail8/job-scheduler
2022-03-08 16:42:15 INFO     Executing "git rev-parse HEAD" in /tmp/tmp8d7oail8/job-scheduler
2022-03-08 16:42:15 INFO     Checked out https://github.com/opensearch-project/job-scheduler.git@main into /tmp/tmp8d7oail8/job-scheduler at ec916373d2a20c268ff8e49a82bbadfbbbfb5c5b
2022-03-08 16:42:16 INFO     Executing "bash /tmp/tmp8d7oail8/job-scheduler/scripts/build.sh -v 1.3.0 -p linux -a x64 -s true -o builds" in /tmp/tmp8d7oail8/job-scheduler
+ getopts :h:v:s:o:p:a: arg
+ case $arg in
+ VERSION=1.3.0
+ getopts :h:v:s:o:p:a: arg
+ case $arg in
+ PLATFORM=linux
+ getopts :h:v:s:o:p:a: arg
+ case $arg in
+ ARCHITECTURE=x64
+ getopts :h:v:s:o:p:a: arg
+ case $arg in
+ SNAPSHOT=true
+ getopts :h:v:s:o:p:a: arg
+ case $arg in
+ OUTPUT=builds
+ getopts :h:v:s:o:p:a: arg
+ '[' -z 1.3.0 ']'
+ [[ true == \t\r\u\e ]]
+ VERSION=1.3.0-SNAPSHOT
+ '[' -z builds ']'
+ ./gradlew publishToMavenLocal -Dopensearch.version=1.3.0-SNAPSHOT -Dbuild.snapshot=true
Downloading https://services.gradle.org/distributions/gradle-7.3.3-bin.zip
...........10%...........20%...........30%...........40%...........50%...........60%...........70%...........80%...........90%...........100%

FAILURE: Build failed with an exception.

* Where:
Build file '/tmp/tmp8d7oail8/job-scheduler/build.gradle' line: 28

* What went wrong:
A problem occurred evaluating root project 'opensearch-job-scheduler'.
> Failed to apply plugin class 'org.opensearch.gradle.info.GlobalBuildInfoPlugin'.
   > Could not create plugin of type 'GlobalBuildInfoPlugin'.
      > Could not generate a decorated class for type GlobalBuildInfoPlugin.
         > org/gradle/jvm/toolchain/JavaInstallation

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org/

BUILD FAILED in 7s
2022-03-08 16:42:23 ERROR    Error building job-scheduler, retry with: ./build.sh manifests/1.3.0/opensearch-1.3.0.yml --component job-scheduler --snapshot
Traceback (most recent call last):
  File "./src/run_build.py", line 79, in <module>
    sys.exit(main())
  File "./src/run_build.py", line 67, in main
    builder.build(build_recorder)
  File "/var/jenkins/workspace/distribution-build-opensearch/src/build_workflow/builder_from_source.py", line 54, in build
    self.git_repo.execute(build_command)
  File "/var/jenkins/workspace/distribution-build-opensearch/src/git/git_repository.py", line 83, in execute
    subprocess.check_call(command, cwd=cwd, shell=True)
  File "/usr/local/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'bash /tmp/tmp8d7oail8/job-scheduler/scripts/build.sh -v 1.3.0 -p linux -a x64 -s true -o builds' returned non-zero exit status 1.
```

**Comment by peterzhuamazon** [comment]
Seems like it is fixed now in https://github.com/opensearch-project/opensearch-build/pull/1717.
New error in: https://github.com/opensearch-project/opensearch-build/issues/1721

Thanks.
